.gitignore
README.md
rebar.config
sample-configs/variable-subst.conf
src/hocon.erl
src/hocon_parser.yrl
src/hocon_scanner.xrl

https://github.com/emqx/hocon/issues/11
In this change, we find `key` at a scanner level. Otherwise the parser would be hard to distinguish `key` from `string`. 
For example
```
a=foo
b=${a}bar"baz"
c=baz
```
the tokens for this HOCON would be
```
string = string string = variable string string string string = string
```
To parse this, we have to tell the parser that `string is key only when = operator follows`, which is hard to describe in yecc (because of shift/reduce conflicts).
By introducing `key` at a scanner level, now the tokens are
```
key string key variable string string string key string
```

feat(src): support variable substitution and concatenation

---

src/hocon.erl
src/hocon_parser.yrl
src/hocon_scanner.xrl
test/hocon_tests.erl

`look-forward variable substitution`
```
a = x
b = ${c}
c = ""
c = ${a}${b}
```
( this is #{a => <<"x">>,b => <<>>,c => <<"x">>})
`array concatenation`
```
a=[1, 2][3, 4]
```
( this is #{a => [1,2,3,4]})
`object concatenation`
```
a={b=1}{c=2}
```
( this is #{a => #{b => 1,c => 2})
Check tests for more examples.

feat(src): support look-forward variable subst, object and array concatenation

---

sample-schemas/demo_schema.erl
src/hocon.erl
src/hocon_schema.erl

Sometimes fields in hocon file many have only one level like:
```
{id: 123}
```
This PR adds the support for writing schema for the above example as:
```
structs() -> ["id"].
fields("id") ->
[fun(mapping) -> "id";
(type) -> integer();
(_) -> undefined
end].
```

feat(hocon_schema): schema for single level fields

---

sample-schemas/demo_schema.erl
src/hocon_schema.erl
test/hocon_schema_tests.erl

refactor(hocon_schema): allow plain map (not richmap) as for check
This commit adds APIs check_plain/2, check_plain/3 to hocon_schema
module which allows checking plain-map (instead of richmap) as
config input.
The old implementation has a mixed global and partial mutation
of the input config (richmap), so the majority of this commit
is mainly to refactor the map API implementation, in order to
gain a more clear picture of both the shcema stack and the data
stack.

feature: add hocon_schema:check_plain/2|3

---

rebar.config
sample-schemas/demo_schema.erl
src/hocon_schema.erl
test/hocon_cli_tests.erl
test/hocon_schema_tests.erl
test/hocon_test_lib.erl

The idea of using function clauses for field schema is to promote
reusable types. However from the observation, we have already started
creating a lot of anonymous functions. i.e. FAILED.
Now map is supported to declare a schema to be more clean.
e.g. a schema can be as simple as: `#{type => string()}`.
instead of having to write `fun(type) -> string(); (_) -> undefined end`
NOTE: structs fields are still NOT to be nested.
i.e. `structs()` is still to return a list of names,
and then call `fields(Name)` to get fields.
i.e. there is no strong argument to support
`#{struct_name => [{field1, #{type => string()}}]}`

Feat support map schema

---

src/hocon_schema.erl
test/hocon_schema_tests.erl

prior to this change, all structs must ave a non-empty namespace
this commit added a 'virutal' so the input of map or check APIs
is not forced to be wrapped as a value of the field name

feat: support virtual root name

---

src/hocon_schema.erl
test/hocon_schema_tests.erl

Also allowed validators to return `true | false`.
Then validator crash is treated as failure.

fix: allow multiple validators in schema

---

sample-schemas/demo_schema.erl
sample-schemas/emqx_management_schema.erl
sample-schemas/emqx_schema.erl
src/hocon_schema.erl
src/hoconsc.erl
test/hocon_schema_tests.erl

mainly about:
1. test coverage 100%
2. throw exception for unknown fields (a filed found in data but not in schema)
3. throw exception if `nullalbe` spec of a field is `true` but it's not found in data
4. improve deep_put performance
5. added a enum type, return define schema using atoms, return atoms after check.
6. environment variable override is logged at info level

make it beautiful

---

src/hocon_cli.erl
src/hocon_schema.erl
test/hocon_cli_tests.erl
test/hocon_schema_tests.erl

Prior to this PR, the hocon_cli's `generate` command prints `run_erl` boot command args to stdio and expect Erlang node's boot script to capture it and use it n `run_erl`.
The main reason I believe was that the `generate` command takes a system time and use it as a part of the generated file names. However the disadvantages of this approach are:
* Logs have to be printed to stderr
* Not shellcheck friendly as the captured stdout line has spaces, and must be split when used as `run erl`
Now the node boot script is forced to decide the next (new) name of the files to be generated by calling the `now_time` command.

Feat cli user decide file names

---

src/hocon_schema.erl
src/hoconsc.erl
test/hocon_schema_tests.erl

prior to this change, references are only allowed to be string names
e.g. {field1, "sub_struct_name"}, but not atom like:
{field1, sub_struct_name}.
This creates some inconsistency because we allow using atoms for
struct names.
After this change, references can be be {ref, AtomOrStringName} tuples.

feat(hocon_schema): Add support for lcoal and remote referencing

---

src/hocon_schema_builtin.erl

This header contains some internal definitions that can change in the future without notice.

chore(typerefl): Don't include a private header

---

src/hocon_schema.erl
test/hocon_schema_tests.erl

Move the handling of options for `atom_key` and `return_plain` into `hocon_schema:map/4`.

opts atom_key and return_plain not working for hocon_schema:map/4

---

src/hocon_schema.erl
test/hocon_schema_tests.erl

Sometimes one may want to generate the config and also return the mapped config.
For example when updating the config, I want to use the following code to generate a hocon config,
apply the app envs, and also save the mapped config in map() format:
```
{AppEnvs, MappedConf} = hocon_schema:map(emqx_schema, Conf, all, #{}),
Translated = hocon_schema:translate(emqx_schema, MappedConf, AppEnvs),
lists:foreach(fun({AppName, Envs}) ->
[application:set_env(AppName, Par, Val) || {Par, Val} <- Envs]
end, hocon_schema:nest(Translated)),
emqx_config:put(hocon_schema:richmap_to_map(MappedConf))
```
We can export the `hocon_schema:nest/1` to allow this.

feat(hocon_schema): add hocon_schema:map_translate/3

---

etc/trailing-comma.conf
src/hocon.erl
src/hocon_scanner.xrl
src/hocon_token.erl
test/hocon_tests.erl

fixes #98 
having `}` or `]` in comment affects tokeniser,
and the fix in #99 causes syntax error when trailing comma is followed by a comment.

fix(parser): delete trailing comma after token scan

---

src/hocon.erl
src/hocon_cli.erl
src/hocon_token.erl
test/hocon_tests.erl

in syntax, scan, parse error messages, log line number before the filename.
also removed filename quotes (changed from `~p` to `~s`)

Refactor refine error logs

---

src/hocon_schema.erl
test/hocon_cli_tests.erl
test/hocon_schema_tests.erl

Just want to set the array values using environment, like this:
```
EMQX_CLUSTER__STATIC__SEEDS="[emqx@node1.emqx.io, emqx@node2.emqx.io]" sh -x _build/emqx/rel/emqx/bin/emqx console
```

feat(hocon_schema): support set array value using env

---

src/hocon_parser.yrl
src/hocon_scanner.xrl
src/hocon_schema.erl
test/hocon_tests.erl

The parser crashed when reporting the `parse_error`:
```
5> hocon:binary("abc ab", #{}).
(<0.277.0>) call hocon_token:parse([{string,1,<<"abc">>},{endstr,1,<<"ab">>}],#{filename => [undefined],path => ['$root']}) ({hocon_util,pipeline,3})
(<0.277.0>) exception_from {hocon_token,parse,2} {error,function_clause}
** exception error: no function clause matching io_lib:write_string1(unicode_as_unicode,<<"abc">>,34) (io_lib.erl, line 581)
in function  io_lib:write_string/2 (io_lib.erl, line 553)
in call from hocon_parser:yeccerror/1 (/Users/liuxy/kerl/23.2.5/lib/parsetools-2.2/include/yeccpre.hrl, line 135)
in call from hocon_parser:yeccpars0/5 (/Users/liuxy/kerl/23.2.5/lib/parsetools-2.2/include/yeccpre.hrl, line 57)
in call from hocon_token:parse/2 …
```

fix(parser): the hocon parser crashed on reporting the 'parse_error'

---

src/hocon.erl
src/hocon_cli.erl
src/hocon_schema.erl
src/hocon_token.erl
test/hocon_cli_tests.erl
test/hocon_schema_tests.erl
test/hocon_tests.erl

for unknown data fields and field values failed at validation,
now the `map`, `check` and `check_plain` APIs report data origin metadata
such as file name (if loaded from hocon file), os environment name, etc.

feat(hocon_schema): report source value location in errors

---

src/hocon_schema.erl
test/hocon_schema_tests.erl

Use `hocon_schema:check_plain/3` to fill the default values (not converted by convertors) to a map:
```
(emqx@127.0.0.1)2> hocon_schema:check_plain(emqx_schema, #{<<"alarm">> => #{}}, #{nullable => true}).
#{<<"alarm">> =>
#{<<"actions">> => [log,publish],
<<"size_limit">> => 1000,<<"validity_period">> => "24h"},
...
```

feat(schema): add option 'no_conversion' to hocon_schema:check_plain/3

---

src/hocon_schema.erl
test/hocon_schema_tests.erl

prior to this fix, only primitive value fileds (leaf-nodes) are allowed
to declare 'nullable'.
non-primitive values fields such as sub-struct (reference) fields'
'nullable' property had no effect.
this commit made the schema check to take all field's 'nullable'
property into account.
in many cases, a parent level field's 'nullable' property should
mask all children fields (so they do not have to all declare to
be 'nullable' recursively). however to be backward compatible
(to be able to generate configs from default values),
we had to introduce a new property-value `{true, recursively}`

fix(hocon_schema): allow non-primitive fields to be nullable

---

include/hoconsc.hrl
src/hocon_schema.erl
src/hoconsc.erl
test/hocon_schema_tests.erl

In order to support plugable configuration, sometimes we need to
delay the schema check of config at plugable app's runtime

feat(hocon_schema): Add a 'lazy' type

---

sample-schemas/demo_schema2.erl
src/hocon_md.erl
src/hocon_schema.erl
src/hocon_schema_doc.erl
test/hocon_schema_tests.erl

Added a `namespace/0` behaviour callback so the generated doc headlines can have more readable prefix.
Also changed from `.` to `:` for namespace & name delimiter to follow EMQX's convention.

feat: add doc namespace

---

include/hoconsc.hrl
sample-schemas/emqx_auth_http_schema.erl
sample-schemas/emqx_auth_jwt_schema.erl
sample-schemas/emqx_auth_ldap_schema.erl
sample-schemas/emqx_auth_mnesia_schema.erl
sample-schemas/emqx_auth_mongo_schema.erl
sample-schemas/emqx_schema.erl
src/hocon_schema.erl
src/hocon_schema_doc.erl
src/hoconsc.erl
test/hocon_schema_doc_tests.erl
test/hocon_schema_tests.erl

prior to this pr, we had to use single-filed structs like `[{$name, Schema}]` to support `map`-like types
i.e. a struct without pre-defined field names.
it worked fine, but it's a bit hard to declare as you'd need to define an extra level of reference field/type
and it's ugly in generated document.
this PR adds a `hoconsc:map/2` type to simplify schema definition also to beautify the generated doc.
example doc:

refactor: map type for wildcard fields

---

src/hocon_schema.erl
test/hocon_schema_tests.erl

For those who (frequently) call the hocon_schema:check function, provide an option to have it not check the env from os.
I check schema frequently by minirest api but without env.

feat(options): support env_override options to skip env override

---

src/hoconsc.erl

Check if args is a hocon type.
Use `hocon_schema:field_schema(#{"bar" => foo}, good) ` will crash.
so I need check the input is a hocon type first.

feat(hoconsc): is_type/1 to check if input is a hocon type

---

src/hocon_schema.erl
test/hocon_schema_tests.erl

in case of `only_fill_defaults`, we do not keep the converted value
in returned results when validating recursively.
for non-primtive values, there is no way to validate them, because the validator callbacks expect converted value.

fix(schema): do not validate if no_conversion for non-primtive

---

sample-schemas/emqx_auth_mongo_schema.erl
src/hocon_schema.erl
test/hocon_schema_tests.erl

before this change, `array` elements can not be overridden by environment variables
the work around was to use `map("id", ElementType)` type instead.
for instance, if we want to override the first element of an array `["element1", "element2"]` to `"elementA"`,
we'd have work with `#{<<"1">> => "element1", <<"2">> => "element2"}`
so that the elements can be set as `export ENV_NAMESPACE__1="elementA"`.
this PR made it possible to override array elements directly.

refactor: apply env for array elements

---

sample-schemas/demo_schema3.erl
src/hocon_schema.erl
test/hocon_schema_tests.erl

hocon_schema can deal with two kinds of array representations
```
% plain-list
[1, 2, 3]
```
and
```
% indexed-map
#{<<"1">> => 1, <<"2">> => 2, <<"3">> => 3}
```
prior to this change, for environment overrides, we convert plain-list to indexed-map as an intermediate value
this causes some trouble for user who wish to return this intermediate value (i.e. `only_fill_defaults` option set to `true`).
this PR makes it respect the input format even for the intermediate value.

Fix schema handling

---

SCHEMA.md
sample-schemas/demo_schema.erl
sample-schemas/demo_schema3.erl
sample-schemas/emqx_schema.erl
src/hocon.erl
src/hocon_cli.erl
src/hocon_schema.erl
src/hocon_schema_doc.erl
src/hocon_util.erl
test/hocon_schema_doc_tests.erl
test/hocon_schema_tests.erl
test/hocon_tests.erl

1. Made `apply_override_envs` default to `false`, since `false` is more commonly used than `true`
1. Added `hocon_schema:merge_env_overrides/4` so we can merge base + overrides without type checks.
1. Removed per-field customisable env variable name (since it's not possible to to apply without type check, i.e contradicting [1]).
1. Support array element override from HOCON values.
Prior to this, `a=[], a.1=1`
is parsed to `#{<<"a">> => #{<<"1">> => 1}}`,
now it's `#{<<"a">> => [1]}`.
This behaviour is consistent to: `a=[]` with env override `export EMQX_A__1=1`

Feat support apply envs without defatuls

---

src/hocon_md.erl
src/hocon_schema_doc.erl

1. vuepress does not index (at leat not by default) heading weight > 2, all struct names are adjusted to weight = 2
2. vuepress's local reference uses `-` for `:`, but not `''` (empty)

FIx markdown doc for vuepress

---

SCHEMA.md
sample-schemas/demo_schema.erl
sample-schemas/emqx_schema.erl
src/hocon.erl
src/hocon_cli.erl
src/hocon_maps.erl
src/hocon_schema.erl
src/hocon_tconf.erl
src/hocon_util.erl
test/hocon_cuttlefish_compatibility_tests.erl
test/hocon_maps_tests.erl
test/hocon_tconf_tests.erl
test/hocon_tests.erl
test/hocon_util_tests.erl

`hocon_schema` module is split to:
1. `hocon_maps`: for map and richmap
2. `hocon_schema`: for hocon schema itself
3. `hocon_tconf`: as in typesafe-config for config mapping and checking

Refactor: split hocon_schema module

---

src/hocon.erl
src/hocon_maps.erl
src/hocon_tconf.erl
src/hocon_token.erl
src/hocon_util.erl

deep_merge/2 is generic enough for deep_map_merge/2
deep_map_merge was to merge map array elements when the array
from the second arg is a indexed-array
all the existing cases where deep_map_merge was used had no
indexed-array

refactor: moved deep_merge/2 to hocon_maps and deleted deep_map_merge/2

---

src/hocon_maps.erl
src/hocon_pp.erl
src/hocon_schema.erl
src/hocon_tconf.erl
test/hocon_maps_tests.erl
test/hocon_pp_tests.erl
test/hocon_tconf_tests.erl

config `/tmp/a.conf`:
```
foo=[a,b]
f1=1
```
flat-dump:
```
f1 = 1 # /tmp/a.conf:2
foo.1 = "a" # /tmp/a.conf:1
foo.2 = "b" # /tmp/a.conf:1
```
this will be useful for troubleshooting

feat: add hocon_pp:flat_dump

---

include/hocon.hrl
include/hocon_private.hrl
include/hoconsc.hrl
sample-schemas/demo_schema3.erl
sample-schemas/emqx_schema.erl
src/hocon.erl
src/hocon_cli.erl
src/hocon_md.erl
src/hocon_postprocess.erl
src/hocon_pp.erl
src/hocon_scanner.xrl
src/hocon_schema.erl
src/hocon_schema_builtin.erl
src/hocon_schema_cuttlefish.erl
src/hocon_schema_html.erl
src/hocon_schema_json.erl
src/hocon_schema_md.erl
src/hocon_token.erl
src/hocon_util.erl
src/hoconsc.erl
test/hocon_cli_tests.erl
test/hocon_cuttlefish_compatibility_tests.erl
test/hocon_pp_tests.erl
test/hocon_schema_html_tests.erl
test/hocon_schema_md_tests.erl
test/hocon_test_lib.erl
test/hocon_tests.erl

fixes https://github.com/emqx/hocon/issues/174
make possible to dump hocon schema to a JSON compatible map.
i.e. this lib itself does not have a JSON lib dependency,
the return value of `hocon_schema_json:gen/1` can be fed to any JSON encoder jsx, jiffy, jsone etc. 
this  JSON dump can be useful in frontend  UI  rendering for post forms .
also, with a bit of javascrpt programming, the configuration document page can be rendered directly from the JSON instead of rendering a markdown file.

feat: make json compatible schema dump

---

rebar.config
sample-schemas/emqx_auth_mongo_schema.erl
sample-schemas/emqx_schema.erl
src/hocon_schema.erl
src/hocon_tconf.erl
test/hocon_tconf_tests.erl

prior to this change, all expected fields are hinted in the exception
when there is an unknown field name.
e.g.
input = [a, b, x], schema = [a, b, c]
hint: unknnwon = [x], expected = [a, b, c]
with this fix, the fields which matches the schema are excluded from
the hint
e.g.
input = [a, b, x], schema = [a, b, c]
hint: unknown = [x], expected = [c]

fix: better type check exception

---

src/hocon_tconf.erl

Without converting the message iolist to a binary, the output error
message is hard to read.
Example:
```
[error] [105,110,112,117,116,45,99,111,110,102,105,103,58,10,"undefined",10,[35,123,[["exception"," => ",[123,["badmap",44,"undefined"],125]],44,10,["  "],["field"," => ","server"],44,["path"," => ","\"authorization.sources.1\""],44,10,["  "],["reason"," => ","failed_to_check_field"]],125],10]
escript: exception error: #{exception => {badmap,undefined},
field => server,path => "authorization.sources.1",
reason => failed_to_check_field}
in function  hocon_tconf:boxit/2 (/emqx/deps/hocon/src/hocon_tconf.erl, line 816)
in call from hocon_tconf:maybe_mkrich/3 (/emqx/deps/hocon/src/hocon_tconf.erl, line 822)
in call from hocon_tconf:map_field_maybe_convert/5 …
```

fix(log): convert error message to binary before logging

---

include/hocon.hrl
include/hoconsc.hrl
src/hocon_schema.erl

1. schema can define as :
```erlang
#{roots => [{"val", hoconsc:map(key, string())}]},
```
the `fields` is not required.
2. add ?R_REF/1 ?MK/1 ?MK/2 macro:
we do a lot of import actions like:
```erlang
-import(hoconsc, [mk/1, mk/2, ref/1, ref/2, array/1, enum/1]).
```
we can use macro to replace the `import`.

Fix: schema spec

---

include/hoconsc.hrl
src/hocon_tconf.erl
test/hocon_tconf_tests.erl

we should limit map's key as `^[A-Za-z0-9]+[A-Za-z0-9-_]*$`.
otherwise :
```yaml
"zones" {
[20013,22269] {
"conn_congestion" {"enable_alarm" = true, "min_alarm_sustain_duration" = "1m"}
"flapping_detect" {
"ban_time" = "5m"
"enable" = false
"max_count" = 15
"window_time" = "1m"
}
```

feat: limit map's key as ^[A-Za-z0-9]+[A-Za-z0-9-_]*$

---

src/hocon_schema.erl
src/hocon_tconf.erl
test/hocon_tconf_tests.erl

If the namespace of multiple modules is undefined(the same namespace), the order of structs will be mixed up.

fix: struct order error if namespace is undefined

---

rebar.config
src/hocon_tconf.erl

the validation_error return `path` fields.
the translation_error return `value_path` fields. 
I hope these 2 keys can be unified into one.

chore: replace trans_error's value_path with path(same as validate_error

---

SCHEMA.md
src/hocon_tconf.erl
test/hocon_tconf_tests.erl

Threat throw as an expected failure. don't return stacktrace.

feat: allow early return when throw in validations/translations

---

src/hocon_schema.erl
src/hocon_schema_example.erl
src/hocon_schema_json.erl
src/hocon_tconf.erl
test/hocon_tconf_tests.erl

typical large union type check error: 
none of the members had the input fields.
prior to this change, all expected fields, and received fields are dumped.
this PR changes to only print first 1 or 2 fields and use `...` to replace the 3rd (and more)

refactor: simplify union mismatch error

---

src/hocon_schema.erl
src/hocon_schema_json.erl
src/hocon_tconf.erl
test/hocon_tconf_tests.erl

related: https://github.com/emqx/emqx/issues/8672
The field schema is kept, so the old configuration will continue to be checked OK.
Deprecated field value will be dropped from type-check result,
so the application code should not need to deal with unexpected fields.

feat: add field deprecation

---

src/hocon_token.erl
test/data/invalid-utf8.conf
test/data/unicode-utf8.conf
test/hocon_tests.erl

Throw more clear logs for scanning invalid utf8.
We can't guarantee that it's all invalid utf8  when the `Input` is from HTTP API.
```erlang
5.0.7-gfdbf8c1c(emqx@127.0.0.1)>jsx:decode(<<"{\"test\":\"® \"}"/utf8>>).
#{<<"test">> => <<"® "/utf8>>}
5.0.7-gfdbf8c1c(emqx@127.0.0.1)2> jsx:decode(<<"{\"test\":\"® \"}">>).
#{<<"test">> => <<239,191,189,32>>}
```

chore: make scan invalid utf8 error more clear

---

src/hocon_tconf.erl
test/hocon_tconf_tests.erl

Converter returning 'undefined' has no effect, but should not crash.

fix(tconf): allow converter to return 'undefined'

---

src/hocon_maps.erl
src/hocon_tconf.erl
test/hocon_tconf_tests.erl

Prior to this fix, the overrides of array values can not overlap.
for example: below overrides will result `#{foo => #{array => [<<"x">>]}}`
```
EMQX_FOO_ARRAY = [a, b]
EMQX_FOO_ARRAY_1 = x
```
after this fix, the result is `#{foo => #{array => [<<"x">>, <<"b">>]}}`

fix(tconf): allow overriding environment variables names to overlap

---

src/hocon_schema.erl
src/hocon_tconf.erl
test/hocon_tconf_tests.erl

Make parsed results possible to be converted back to serializable format.
Also possible to upgrade older version raw results to newer version.

1222 feat support reverse convert

---

src/hocon_tconf.erl

the override env meta was removed too early causing the hocon_cli generation not able to log anything.

fix: do not remove env meta before checking

---

src/hocon_cli.erl
test/hocon_cli_tests.erl

In PR #219 the value wrapper for env override metadata is moved to richmap meta data,
as a result, the wrapping struct's meta data is propagated down to the primitive fields.
but one thing was forgotten (not released yet): the override logging started to repeating the same info at different levels.
This PR mutes the struct level logging (because it lacks of `sensitive` information at wrapping object level)
and only log primitive values instead.
before this change:
```
authentication.1 = EMQX_AUTHENTICATION__1 = #{<<“backend”>> => <<“mysql”>>,<<“database”>> => <<“emqx”>>,<<“enable”>> => true,<<“mechanism”>> => <<“password_based”>>,<<“password”>> => <<“emqx”>>,<<“password_hash_algorithm”>> => #{<<“name”>> => <<“sha256">>,<<“salt_position”>> => <<“prefix”>>},<<“query”>> => <<“SELECT …
```

refactor: do not log overriding structs

---

src/hocon_tconf.erl
test/hocon_tconf_tests.erl

Prior to this change the re-wrapping of validation_error context may cause the real data path to be overwrite.

fix: avoid path shadow in union check errors

---

src/hocon_tconf.erl
test/hocon_tconf_tests.erl

prior to this fix, the matched_type error reason from deeper-stack union check is shadowed by uper layer union check

chore: fix type path shadow

---

src/hocon_schema_json.erl
src/hocon_schema_md.erl

mappings are quite opaque from user's perspective

refactor: remove mapping from generated docs

---

src/hocon_tconf.erl
test/hocon_tconf_tests.erl

keep ENV's invalid hocon value as binary when we store raw config.
before:
```bash
EMQX_STATSD__SERVER='127.0.0.1:8124' ./bin/emqx console
> emqx:get_raw_config([statsd,server]).
"127.0.0.1:8124"
> emqx:get_raw_config([statsd,server]).
<<"127.0.0.1:8124">>
```
Report from : [StatsD server address changed to array format](https://emqx.atlassian.net/browse/EMQX-9154)

feat: change env's invalid hocon value from string to binary

---

src/hocon_maps.erl
src/hocon_schema.erl
src/hocon_schema_json.erl
src/hocon_tconf.erl
test/hocon_schema_aliases_tests.erl
test/hocon_schema_json_tests.erl
test/hocon_tconf_tests.erl

With aliases supported, we can more freely rename fileds. e.g.
if a field is renamed to `new_field`, all we need to do is to keep the old name `field` as an alias in the schema like this:
`{new_filed, #{type => integer(), aliases => [field]}`

feat: add struct (root included) field name aliases

---

sample-schemas/emqx_schema.erl
src/hocon_schema_example.erl
test/hocon_schema_example_tests.erl

Fix:
```
{"init terminating in do_boot",{function_clause,[{hocon_schema_example,'-fmt_field/3-fun-1-',[#{elements=>#{kind=>primitive,name=><<"atom()">>},kind=>array}],[{file,"hocon_schema_example.erl"},{line,139}]},{lists,map,2,[{file,"lists.erl"},{line,1243}]},{lists,map,2,[{file,"lists.erl"},{line,1243}]},{hocon_schema_example,fmt_field,3,[{file,"hocon_schema_example.=ERROR REPORT==== 10-Apr-2023::21:18:12.910199 ===
Error in process <0.9.0> with exit value:
{function_clause,
[{hocon_schema_example,'-fmt_field/3-fun-1-',
[#{elements => #{kind => primitive,name => <<"atom()">>},
kind => array}],
[{file,"hocon_schema_example.erl"},{line,139}]},
{lists,map,2,[{file,"lists.erl"},{line,1243}]},
{lists,map,2,[{file,"lists.erl"},{line,1243}]},
{hocon_schema_example,fmt_field,3, …
```

fix: crash example on union([array[atom()])

---

src/hocon_schema.erl

the function is exported twice.

chore: fix compile warning

---

etc/unescape.conf
src/hocon_pp.erl
test/hocon_pp_tests.erl

Before: `hocon_pp:do/2` return unicode as :
```
F = #{<<"a">> => <<"b=\"1\" ">>,
<<"desc">> =>
<<98,97,114,32,230,181,139,232,175,149,13,10,228,184,147,
9,231,148,168,32,102,111,111,10>>,
<<"sql_laitin1">> => <<"SELECT * FROM t/1">>,
<<"sql_laitin1_with_escape_1">> =>
<<"SELECT * FROM \"t/1\"">>,
<<"sql_laitin1_with_escape_2">> =>
<<"SELECT * FROM \\\"t/1\\\"">>,
<<"sql_unicode_with_escape_1">> =>
<<83,69,76,69,67,84,32,42,32,70,82,79,77,32,34,116,47,49,
34,32,87,72,69,82,69,32,99,108,105,101,110,116,105,100,
32,61,32,34,45,230,181,139,232,175,149,228,184,147,231,
148,168,45,34>>,
<<"sql_unicode_with_escape_2">> =>
<<83,69,76,69,67,84,32,42,32,70,82,79,77,32,92,34,116,47,
49,92,34,32,87,72,69,82,69,32,99,108,105,101,110,116,
105,100,32,61,32,34,45,230,181,139,232,175,149,228,184, …
```

fix: save utf8 to file garbled

---

src/hocon_tconf.erl
test/hocon_tconf_tests.erl

1. Define a union type `union([ref(log_file_handler),map(name, ref(log_file_handler))]`
2. Convert `ref(log_file_handler)` to `map(name, ref(log_file_handler))`
3. Crash
```
**throw:{#{roots =>
[{f1,#{converter => #Fun<hocon_tconf_tests.57.87224844>,
type =>
{union,[{ref,hocon_tconf_tests,bar},
{map,name,{ref,hocon_tconf_tests,bar}}]}}}]},
[#{kind => validation_error,
mismatches =>
#{"bar" =>
#{kind => validation_error,path => "f1",
reason => unknown_fields,unknown => "default",
unmatched => "host,union_with_default"},
"name" =>
#{kind => validation_error,
location => #{line => 1},
path => "f1.field1",reason => bad_value_for_struct,
value => <<"foo1">>}},
path => "f1",reason => matched_no_union_member}]}
output:<<"">>
```
More detail see `test/hocon_tconf_tests.erl`

fix: convert to different union type crash

---

src/hocon_pp.erl
test/hocon_pp_tests.erl

fixes: Part of https://emqx.atlassian.net/browse/EMQX-9546
https://emqx.atlassian.net/browse/EMQX-9999
> file:write_file("test.conf",hocon_pp:do(#{<<"test">> => #{<<"测试"/utf8>> => 1}},#{})).
before: 
```
test {[27979,35797] = 1}
```
after:
```
test {"测试" = 1}
```

fix: bad pp unicode map keys

---

src/hocon_token.erl
test/hocon_tests.erl

prior to this change, the scan error is formated as a utf8 binary string, this caused some unreadable error messages if the error is not formated to console using ~ts.
this commit changes the error report to a map, in which, at least the line number and file paht/name are universally printable --- this is usually enough to find the error.

fix(hocon_token): fix scan error message format

---

src/hocon_tconf.erl
test/hocon_tconf_tests.erl

```erlang
1> Sc = #{roots => [{"discovery_strategy", hoconsc:mk(hoconsc:enum([manual, static, dns, etcd, k8s, mcast]),#{default => manual })}]}.
#{roots =>
[{"discovery_strategy",
#{default => manual,
type => {enum,[manual,static,dns,etcd,k8s,mcast]}}}]}
% The `discovery_strategy` has  a atom value(`manual`) if fallback to default.
2> hocon_tconf:make_serializable(Sc, #{}, #{}).
#{<<"discovery_strategy">> => manual}
% Read from hocon file will get a binary value <<"manual">>.
3> {ok, Map} =hocon:binary(<<"discovery_strategy = manual">>).
{ok, #{<<"discovery_strategy">> => <<"manual">>}}
4> hocon_tconf:make_serializable(Sc, Map, #{}).
#{<<"discovery_strategy">> => <<"manual">>}
```
So we have standardized on "binary" value.
PS: We can't get atom value from `hocon:binary/1` map's value …

feat: transform atom to binary if serializable=true

---

sample-schemas/emqx_management_schema.erl
sample-schemas/emqx_schema.erl
src/hocon_schema_builtin.erl
test/hocon_schema_builtin_tests.erl

When an integer value is read from a hocon file or default value, `typerelf:from_string` conversion is not executed, resulting in an unchecked boundary condition.
More detail see hocon_schema_builtin_tests.erl's `to_ip_port/1` function.

fix: builtin type don't convert from_string when value is integer

---

src/hocon_tconf.erl
test/hocon_tconf_tests.erl

So that things like `{"value":11,"reason":{"expected_type":"1..10"},...` won't be confusing to the user.

fix(tconf): emit `expected` instead of `expected_type` in errors

---

etc/null.conf
src/hocon_pp.erl
test/hocon_pp_tests.erl

Before this fix, `hocon_pp:do(#{val => '12345'}, #{})` would produce invalid HOCON document.

fix(pp): ensure generic atoms printed as strings

---

src/hocon_pp.erl
test/hocon_pp_tests.erl

https://github.com/lightbend/config/blob/main/HOCON.md#unquoted-strings
Fix: https://emqx.atlassian.net/browse/EMQX-10294
Unquoted strings
> A sequence of characters outside of a quoted string is a string value if:
> 
> it does not contain "forbidden characters": '$', '"', '{', '}', '[', ']', ':', '=', ',', '+', '#', '`', '^', '?', '!', '@', '*', '&', '' (backslash), or whitespace.
> it does not contain the two-character string "//" (which starts a comment)
> its initial characters do not parse as true, false, null, or a number.
> Unquoted strings are used literally, they do not support any kind of escaping. Quoted strings may always be used as an alternative when you need to write a character that is not permitted in an unquoted string.
> 
> truefoo parses as the boolean token true …

fix: honor hocon spec for quote string

---

src/hocon_schema.erl

Fix return type for `desc` callback

fix: updates return type for `desc` callback

---

src/hocon_maps.erl
test/hocon_tconf_tests.erl

By using `hocon_tconf:check_plain(Schema, Map, #{atom_key => {true, unsafe}})`, fields and `hoconsc:map` keys are converted to atoms unsafely, while keys in `map()` and their nested values therein are kept as binaries.

feat: add unsafe atom conversion to `hocon_tconf:check_plain`

---

.github/workflows/run_elvis.yaml
.github/workflows/run_test_case.yaml
Makefile
rebar.config
scripts/elvis-check.sh
src/hocon.erl
src/hocon_maps.erl
src/hocon_md.erl
src/hocon_parser.yrl
src/hocon_pp.erl
src/hocon_scanner.xrl
src/hocon_token.erl
test/hocon_tconf_tests.erl
test/hocon_tests.erl

fix: do not split quoted key as path

---

test/hocon_tconf_tests.erl

fixes #33 
so far, only the translated paths are converted to atom in hocon_tconf module.
added a test case to cover it.

test: add eunit case to cover unicode atoms in translated paths

---

sample-schemas/demo_schema6.erl
src/hocon_schema_json.erl
test/hocon_schema_json_tests.erl

In hocon schema, field desc is allowed to be missing and unresolvable. Prior to this fix, the struct desc is allowed to be missing but not unresolvable.
For example, if the desc is resoved from {desc, reference}, but failed. i.e. returned 'undefined', this atom is used in the iodata output which then causes 'badarg' error when getting serialized

fix(schema): Allow unresolvable struct desc

---

src/hocon_maps.erl
src/hocon_tconf.erl
test/hocon_tconf_tests.erl

The Erlang VM only supports [atoms up to 255 bytes](https://www.erlang.org/doc/efficiency_guide/advanced#system-limits), so we should validate the length before attempting the conversion.

fix: validate map field name length before attempting to convert to atoms

---

include/hocon_types.hrl
sample-schemas/demo_schema.erl
src/hocon_schema.erl
src/hocon_schema_example.erl
src/hocon_tconf.erl
src/hoconsc.erl
test/hocon_tconf_tests.erl

feat: add display_name to union type
With typerefl:alias/2, the primitive can be quite descriptive.
Other types are quite self-descriptive too.
Unions however, can get quite big and ugly when:
1. Some old types added for backward compatibility
e.g. we want to document something like "ArrayOf(String)",
but we also support comma separated strings which
can be described in docs but not necessarily show in
the type.
2. When the union is very big, we may want to provide a shorter
name for it.
For example, if all union members are enumerated for a
5-member union, it may look like OneOf(t1,t2,t3,t4,t5).
When using display name, we can do:
"Object (see all possible values below)"

1108 support display type name

---

src/hocon_tconf.erl
test/hocon_tconf_tests.erl

Otherwise it's impossible to tell if the original value existed or not when an obfuscated struct is sent back for comparism.

fix(hocon_tconf): do not obfuscate 'undefined' as "******"

---

README.md
etc/unescape.conf
src/hocon_pp.erl
src/hocon_scanner.xrl
test/hocon_pp_tests.erl
test/hocon_tests.erl

now we can do this:
```
a {
b {
c = """~
line1
line2
line3
~"""
}
}
```
More practical examples:
```
rule_engine {
ignore_sys_message = true
jq_function_default_timeout = 10s
rules {
a_WH_D {
actions = ["http:a_WH_D"]
description = ""
enable = true
metadata {created_at = 1707562385536}
name = ""
sql = """~
SELECT
*
FROM
"#",
"$events/message_delivered",
"$events/message_acked",
"$events/message_dropped",
"$events/client_connected",
"$events/client_disconnected",
"$events/client_connack",
"$events/client_check_authz_complete",
"$events/session_subscribed",
"$events/session_unsubscribed",
"$events/delivery_dropped"~"""
}
rule_rc0w {
actions = [
{
args {
mqtt_properties {}
payload = "${.}"
qos = 0
retain = false
topic = "republish-event/${clientid}"
user_properties = ""
}
function = …
```

0213 multiline string indentation

---

include/hocon_private.hrl
src/hocon_pp.erl
test/hocon_pp_tests.erl

Prior to this refactoring, the pretty-print indentation implementation relies on a lot of binary split and reassembling operations.
This change made the indentation insertion when recursively generating the lines.

refactor: improve indentation rendering

---

src/hocon_pp.erl
src/hocon_schema_json.erl
test/hocon_pp_tests.erl

* Fixed a bug: missing `,` between 'oneliner' struct fields and array elements.
* Make sure the `hocon_pp:do` function  returns a list of `binary()` strings, one for each line -- some callers rely on this contract.
* Do not format as a 'onliner' if map values or array elements has long strings (longer than 40 bytes).
* Sort map fields.
* Avoid generating triple-quote strings when 'onliner' is opted

fix(hocon_pp): ensure the pretty-print result is a list of lines

---

README.md
src/hocon_pp.erl
src/hocon_scanner.xrl
test/hocon_pp_tests.erl
test/hocon_tests.erl

In a indented multiline string, the closing `"""` or `~"""` can be indented less than the other lines.
When parsing the value, the all-space last line should not be used to identify the minimum indentation.
Also implemented more complete support for CRLF newlines in multiline string,
previously, a line with only `\r` is not considered empty hence indented.

fix(hocon_scanner): ignore identation of the closing triple-quote

---

sample-schemas/demo_schema.erl
sample-schemas/emqx_auth_http_schema.erl
sample-schemas/emqx_auth_jwt_schema.erl
sample-schemas/emqx_auth_ldap_schema.erl
sample-schemas/emqx_auth_mnesia_schema.erl
sample-schemas/emqx_auth_mongo_schema.erl
sample-schemas/emqx_auth_mysql_schema.erl
sample-schemas/emqx_auth_pgsql_schema.erl
sample-schemas/emqx_auth_redis_schema.erl
sample-schemas/emqx_management_schema.erl
src/hocon_schema.erl
test/hocon_tconf_tests.erl

The `erlang:function_exported(Schema, namespace, 0)` prevents the module from being loaded in interactive mode.

refactor: make namespace/0 a non-optional export

---

src/hocon_schema.erl

We commonly use `deprecated => {since, "x.y.z"}`, but that is not what the typespec expects.
```
Line 72 Column 50: The call hocon_schema:override(Sc::atom() | fun((_) -> any()) | maybe_improper_list() | tuple() | map(), Override::#{'default':=[], 'deprecated':={'since',[46 | 48 | 53 | 54 | 101,...]}, 'importance':='hidden', 'required':='false', 'type':=_, 'validator':=fun((_) -> 'ok')}) breaks the contract (field_schema(), field_schema_map()) -> field_schema_fun()
```

fix(typespec): fix `hocon_schema:override` typespec

---

src/hocon_pp.erl
test/hocon_pp_tests.erl

Now below strings are quoted (although they are unquoted strings):
1. Strings starts with digits, e.g. "12kb"
2. Strings have `.` or `-`
This is to help other libs (such as golang) which have trouble parsing such values.

refactor: print more string values quoted

---

src/hocon_schema.erl
src/hocon_tconf.erl
test/hocon_schema_example_tests.erl
test/hocon_tconf_tests.erl

Sometimes the default regex for the map key can't suit the circumstances. for example, add a namespace for the key name: namespace_id/resource_id

feat: allow custom the key type in the map type

---

src/hocon_schema.erl

Minor change to replace `function_clause` with a bit more info to track down the error.
Before the change:
```
[error] input-config:
'$hcVal' =>
[#{'$hcTyp' => object,
'$hcVal' =>
#{<<"key">> =>
#{'$hcTyp' => string,'$hcVal' => <<"ts">>,
'$hcMeta' =>
#{line => 45,
filename =>
"/home/thales/dev/emqx/emqx/_build/emqx-enterprise/rel/emqx/data/configs/cluster.hocon"}},
<<"value">> =>
#{'$hcTyp' => string,
'$hcVal' => <<"concat([topic, '/', a.b])">>,
'$hcMeta' =>
#{line => 46,
filename =>
"/home/thales/dev/emqx/emqx/_build/emqx-enterprise/rel/emqx/data/configs/cluster.hocon"}}},
'$hcMeta' =>
#{line => 46,
filename =>
"/home/thales/dev/emqx/emqx/_build/emqx-enterprise/rel/emqx/data/configs/cluster.hocon"}}],
'$hcMeta' =>
#{line => 43,
filename => …
```

chore: add more info to errors

---

include/hoconsc.hrl
src/hocon_schema.erl
test/hocon_tconf_tests.erl

For fields that are meant to be returned in APIs, but are not to have their documentation generated.

feat: add `?IMPORTANCE_NO_DOC` importance

---

src/hocon_tconf.erl
test/hocon_tconf_tests.erl

This fixes the crash like below:
2024-09-06T11:55:41.141104+02:00 [warning] reason: {case_clause,{error,{config_update_crashed,#{reason => failed_to_check_field,path => "actions",exception => {case_clause,{[<<"webhook">>
,<<"webhook">>,<<"webhook">>,<<"webhook">>,<<"webhook">>,<<"webhook">>],[<<"webhook1">>]}},field => <<"http">>}}}}, path: /actions, stacktrace: [{emqx_bridge_v2_api,do_create_or_update_br
idge,5,[{file,"emqx_bridge_v2_api.erl"},{line,1439}]},{minirest_handler,apply_callback,3,[{file,"minirest_handler.erl"},{line,158}]},{minirest_handler,handle,2,[{file,"minirest_handler.er
l"},{line,56}]},{minirest_handler,init,2,[{file,"minirest_handler.erl"},{line,27}]},{cowboy_handler,execute,2,[{file,"cowboy_handler.erl"},{line,41}]},{cowboy_stream_h,execute,3,[{file,"c …

fix: no alias for map fields

---

.github/workflows/run_elvis.yaml
.github/workflows/run_test_case.yaml
rebar.config
src/hocon.app.src
src/hocon_parser.yrl
src/hocon_pp.erl
src/hocon_scanner.xrl
src/hocon_schema_builtin.erl
src/hocon_tconf.erl
test/hocon_schema_builtin_tests.erl

chore: ensure Erlang/OTP 27 compatibility

---

include/hocon.hrl
src/hocon_tconf.erl
test/hocon_tconf_tests.erl

This allows us to compute fields _from checked configurations_, so we may cache arbitrary values we want to associate with the field.  Only `map()`'s and structs may have computed fields attached.  The resulting value is added to a `?COMPUTED` atom key inside the resulting checked configuration.

feat: add computed fields

---

src/hocon_scanner.xrl
test/hocon_pp_tests.erl

Fixes https://emqx.atlassian.net/browse/EMQX-14157

fix: prevent trailing backslash from "eating" triple quotes
