.github/workflows/.gitlint, .github/workflows/run_elvis.yaml, .github/workflows/run_gitlint.yaml, .github/workflows/run_test_case.yaml, .gitignore, elvis-check.sh, elvis.config, src/hocon.erl
example: https://github.com/z8674558/hocon/pull/2
=> run elvis, eunit, gitlint on github actions

README.md
Delete already-done:s
and non-goal:s
=> docs(README): Update TODO list

src/hocon_schema.erl
```
(abc@MBP13)19> log_tracer:translations().
[]
(abc@MBP13)18> {ok, M} = hocon:load("examples/log_tracer.conf", #{format => richmap}).
{ok,#{metadata =>
#{filename =>
"/Users/liuxy/code/emqx_resource/examples/log_tracer.conf",
line => 0}, ...}
(abc@MBP13)19> hocon_schema:generate(log_tracer, M).
[]
```
=> fix(hocon_schema): generate fails if Mod:translations/0 returns an empty list

rebar.config, rebar.lock
=> chore: Bump typerefl version

rebar.config
Fix conversion of string to binary
=> chore(typerefl): Bump version to 0.6.2

src/hocon.erl, test/hocon_tests.erl
https://github.com/emqx/hocon/issues/93
=> fix(hocon): also expand array/concat

src/hocon_schema.erl, test/hocon_schema_tests.erl
If we consider the whole config (app configs merged as a node config) as a struct, 
then the root names are both serving as namespace and field names.
when we started designing `hocon_schema`, it was more to mimic the behaviour of cuttlefish schema,
so we only took namespace into consideration, but did not think of it as a field of its enclosing struct,
as a result, there is a lack of the ability to declare root field's types (only implicitly -- always a struct).
This PR is to make it possible to declare root fields as arrays.
NOTE: there is (so far) no plan to extend the scope to include other types.
=> feat: support root level array type

src/hocon_cli.erl, src/hocon_md.erl, src/hocon_schema.erl, src/hocon_schema_doc.erl, test/hocon_schema_doc_tests.erl
see a full demo generated from https://github.com/emqx/emqx schema module: `emqx_machine_schema`
https://gist.github.com/zmstone/d3ac671ee4e5cc0c4b9d2a41d2b7be90
=> feat(hocon_schema): generate markdown doc from schema

include/hocon_private.hrl, rebar.config, src/hocon.erl, src/hocon_pp.erl, src/hocon_schema_doc.erl, test/hocon_pp_tests.erl
Add hocon value pretty print.
and use it for `default` value in generated docs
sample pretty-print result:
```
cluster {
autoclean = "5m"
autoheal = "on"
discovery = "manual"
name = "emqxcl"
proto_dist = "inet_tcp"
}
listener {
ssl {
acceptors = 16
access {
"1" = "allow all"
}
active_n = 100
cacertfile = "certs/cacert.pem"
certfile = "certs/cert.pem"
dhfile = "certs/dh-params.pem"
fail_if_no_peer_cert = true
handshake_timeout = "15s"
keyfile = "certs/key.pem"
listen = 8883
max_conn_rate = 500
max_connections = 102400
peer_cert_as_username = "cn"
rate_limit = "100KB,10s"
tls_versions = [
"tlsv1.2"
"tlsv1.1"
"tlsv1"
]
verify = "verify_peer"
zone = "external"
}
tcp {
acceptors = 4
active_n = 1000
backlog = 512
listen = "127.0.0.1:11883"
max_conn_rate = 1000
max_connections = 1024000 …
```
=> feat: default value pretty print

priv/doc-template.html, src/hocon_cli.erl, src/hocon_schema.erl, src/hocon_schema_doc.erl, src/hocon_schema_html.erl, test/hocon_schema_html_tests.erl, test/hocon_schema_tests.erl
Created a poorman's HTML template.
for demo: http://maz36.duckdns.org/emqx.html
=> feat: generate html doc

sample-schemas/demo_schema.erl, src/hocon_schema.erl, src/hocon_schema_doc.erl, src/hocon_schema_html.erl
Support document generation for struct (type)
=> feat(schema): Add structs doc

src/hocon_schema_html.erl
make sure the root structs can be referenced from the index pannel
=> feat(docgen): better reference links

sample-schemas/demo_schema.erl, src/hocon_schema.erl, src/hocon_schema_doc.erl, src/hocon_schema_html.erl, test/hocon_schema_tests.erl
when a field is marked 'hidden' in its metadata, it's not displayed in doc
=> feat: support hidden fields

src/hocon_schema.erl
otherwise if an env variable is shared between different union members
there will be duplicated logs
=> fix: only log env overrides after check succeeded

src/hocon_cli.erl, src/hocon_md.erl, src/hocon_schema.erl, src/hocon_schema_doc.erl, src/hocon_util.erl, test/hocon_schema_doc_tests.erl
example doc
https://gist.github.com/zmstone/52365bcd172c8cc4f08fc2ea35eef1a3
=> doc: list paths to fields and env overrides

src/hocon_pp.erl
=> Revert "feat: Pretty print proplist as map"

sample-schemas/demo_schema.erl, src/hocon_tconf.erl, test/hocon_tconf_tests.erl
=> feat: add obfuscate_sensitive_values option

src/hocon_schema_example.erl, src/hocon_schema_json.erl
example sample preview: https://gist.github.com/zhongwencool/8e26a48dcf2c51028f206ee8d1abd12d
=> refactor: refactor example link

src/hocon_schema.erl
fetch schema cache is too slow.
```erlang
Fun = fun() -> {Time, ready} = timer:tc(fun() -> emqx_dashboard_listener:regenerate_minirest_dispatch() end), Time end.
```
before:
```erlang
>[Fun() ||_<-lists:seq(1,20)].
[15150134,18281339,14056930,8864422,8567035,9308259,8592177,
8265742,8621003,9954820,9114140,8974866,9281499,8987957,
8893270,8073501,8420933,8249859,9051064,11860394]
```
after:
```erlang
>[Fun() ||_<-lists:seq(1,20)].
[2294022,2323721,2307445,2326173,2373369,2344453,2413898,
2566971,4224544,3409544,3270445,3131782,6871738,3522499,
3315031,3206544,3560597,3819316,3381605,3134793]
```
=> fix: improve schema cache speed

include/hocon_private.hrl, src/hocon_maps.erl, src/hocon_schema.erl, src/hocon_schema_html.erl, src/hocon_tconf.erl, src/hoconsc.erl, test/hocon_tconf_tests.erl
This makes union type check errors more readable.
see more details here: https://github.com/emqx/emqx/pull/9653
=> feat: union member selector

sample-schemas/demo_schema4.erl, sample-schemas/demo_schema5.erl, sample-schemas/emqx_schema.erl, src/hocon_schema.erl, src/hocon_schema_json.erl, src/hocon_schema_md.erl, test/hocon_schema_example_tests.erl, test/hocon_schema_json_tests.erl
[EMQX-8330](https://emqx.atlassian.net/browse/EMQX-8330)
By adding tags, it'll be (hopefully) easier to manipulate and split a big schema that has been dumped to JSON based on those.
=> feat(tags): add support for tagging schemas

src/hocon_tconf.erl
=> refactor: simplify env parser implementation

.gitignore, include/hocon_types.hrl, include/hoconsc.hrl, rebar.config, src/hocon_schema.erl, src/hocon_schema_json.erl, src/hocon_schema_md.erl, src/hocon_tconf.erl, src/hoconsc.erl, test/hocon_tconf_tests.erl
When a field is `hidden` it would not make sense to fill default value for it.
=> 0322 do not fill default value if hidden

.gitignore, sample-schemas/demo_schema.erl, src/hocon_postprocess.erl, test/hocon_tconf_tests.erl
https://emqx.atlassian.net/browse/EMQX-11485
=> feat: percent support 12.345%

src/hocon_cli.erl, test/hocon_cli_tests.erl
fixes: https://github.com/emqx/emqx-operator/issues/1060
=> 0703 cli print array and map summary

src/hocon_pp.erl, test/hocon_pp_tests.erl
Fixes https://emqx.atlassian.net/browse/EMQX-12838
=> fix: quote `"null"` map keys

.github/workflows/run_test_case.yaml, README.md
There is no plan to support environment variable value interpolation.
=> docs: add limitation about environment variable value interpolation

src/hocon_tconf.erl, test/hocon_tconf_tests.erl
Part of https://github.com/emqx/emqx/pull/15039#discussion_r2049277150
=> feat(computed fields): add option to avoid computing computed fields
